# Generated by Django 5.1.6 on 2025-02-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='design_type',
            field=models.CharField(choices=[('basic', 'Basic Design'), ('sizes', 'Design with Sizes')], default='basic', max_length=10),
        ),
    ]
