# Generated by Django 5.1.6 on 2025-02-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_productsize_design_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='design_type',
        ),
        migrations.AddField(
            model_name='product',
            name='design_type',
            field=models.CharField(choices=[('basic', 'Basic Design'), ('sizes', 'Design with Sizes')], default='basic', max_length=10),
        ),
    ]
