# Generated by Django 5.1.6 on 2025-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_remove_productsize_design_type_product_design_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design_type',
            field=models.CharField(choices=[('basic', 'Basic Design'), ('basic-1', 'Basic Design 1')], default='basic', max_length=10),
        ),
    ]
